configure - cli parameters cpu optimalization improvements

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -5,40 +5,246 @@ CROSS_CC=arm-linux-gnueabihf-gcc
 CROSS_CXX=arm-linux-gnueabihf-g++
 
 function help {
-    echo "configure script for RF24 library."
-    echo "Parameters:"
-    echo "OS=[LINUX|DARWIN] - Operating system."
-    echo "ARCH=<arch> - cpu architecture as passed to --arch to gcc"
+cat <<EOF
+configure script for RF24 library.
+Options:
 
+Help:
+    -h, --help                  print this message
+
+Driver options:
+    --driver=[SPIDEV|MRAA|RPi|LittleWire]
+                                Driver for RF24 library. [configure autodetected]
+
+Building options:
+    --os=[LINUX|DARWIN]         Operating system. [configure autodetected]
+    --soc=[BCM2835|BCM2836|AM33XX|A10|A13|A20]
+                                SoC type to be used. [configure autodetected]
+    --cpu-flags=<CFLAGS>        CPU defining/optimizing flags to be used. [configure autodetected]
+    --extra-cflags=<CFLAGS>     Extra C flags passed to C/C++ compilation. []
+    --extra-ldflags=<LDFLAGS>   Extra C flags passed to linking. []
+    --libname=<LIBNAME>         Library name. [rf24]
+    --c_compiler=<CC>           C compiler. [arm-linux-gnueabihf-gcc][gcc]
+    --cxx_compiler=<CXX>        C++ compiler [arm-linux-gnueabihf-g++][g++]
+
+Installation options:
+    --prefix=<PREFIX>           Installation prefix path. [/usr/local]
+    --lib-dir=<DIR>             Library target installation directory. [PREFIX/lib]
+    --header-dir=<DIR>          Header files target installation directory. [PREFIX/include]
+    --examples-dir=<DIR>        Example files installation directory. [PREFIX/bin]
+    --ldconfig=<LDCONFIG>       Ldconfig binary. Can be set to '' to skip ldconfig step. [ldconfig]
+
+Cross-compilation options:
+    --remote-host=<REMOTE_HOST> Remote hostname for installation.
+    --remote-user=<REMOTE_USER> Remote username for installation. [current user]
+    --remote-port=<REMOTE_PORT> Ssh port of remote machine. [22]
+    --remote=<USER@HOST>        Remote ssh host identification for installation [REMOTE_USER@REMOTE_HOST]
+    --remote-prefix=<RPREFIX>   Remote host installation prefix path. [/usr/local]
+    --remote-lib-dir=<DIR>      Remote library target installation directory [RPREFIX/lib]
+    --remote-header-dir=<DIR>  Remote header files target installation directory. [RPREFIX/include]
+    --remote-ldconfig=<RLDCON>  Remote ldconfig binary filename. Can be set to '' to skip ldconfig call. [ldconfig]
+    --remote-examples-dir=<DIR> Example files remote installation directory. Default: [REMOTE_PREFIX/bin]
+
+EOF
 }
 
 function execute_check {
     if [ "${REMOTE}" ]; then
-        ssh -o 'PreferredAuthentications=publickey' -o 'ConnectTimeout=30' -o 'BatchMode=yes' -o 'StrictHostKeyChecking=no' -p ${REMOTE_PORT} ${REMOTE} $1
+        ssh -o 'PasswordAuthentication=no' -o 'PreferredAuthentications=publickey' -o 'ConnectTimeout=30' -o 'BatchMode=yes' -o 'StrictHostKeyChecking=no' -p ${REMOTE_PORT} ${REMOTE} $1
     else
         eval $1
     fi
 }
 
-params="OS ARCH DRIVER CFLAGS PREFIX REMOTE_PREFIX LIB LIBNAME CC CXX LIB_DIR REMOTE_LIB_DIR HEADER_DIR REMOTE_HEADER_DIR DRIVER_DIR ARCH_DIR REMOTE REMOTE_HOST REMOTE_USER REMOTE_PORT SHARED_LINKER_FLAGS LDCONFIG REMOTE_LDCONFIG EXAMPLES_DIR REMOTE_EXAMPLES_DIR"
-for i in "$@"; do
-    if [ "$i" = "-h" ] || [ "$i" = "--help" ]; then
+function die {
+    echo "[ERROR] $1"
+    exit $2
+}
+
+function detect_machine {
+    local cpu=$(execute_check "uname -m 2>/dev/null")
+    local machine=$(execute_check "cat /sys/firmware/devicetree/base/model 2>/dev/null")
+    local hardware=$(execute_check "grep Hardware /proc/cpuinfo 2>/dev/null")
+    local soc="unknown"
+    local tp="unknown"
+    hardware=${hardware/*:/}
+
+    if [ -z "$cpu" ]; then
+        cpu="unknown"
+    fi
+
+    case $hardware in
+    BCM2708)
+        soc="BCM2835"
+        if [[ $machine == "Raspberry"* ]]; then
+            tp="RPi"
+        fi
+        ;;
+    BCM2709)
+        soc="BCM2836"
+        if [[ $machine == "Raspberry"* ]]; then
+            tp="RPi2"
+        fi
+        ;;
+    sun4i)
+        soc="A10"
+        ;;
+    sun5i)
+        soc="A13"
+        ;;
+    sun6i)
+        soc="A31"
+        ;;
+    sun7i)
+        soc="A20"
+        if [[ $machine == "Banana Pi"* ]]; then
+            tp="BananaPi"
+        elif [[ $machine == "Banana Pro"* ]]; then
+            tp="BananaPro"
+        fi
+        ;;
+    sun8i)
+        soc="A23"
+        ;;
+    sun9i)
+        soc="A80"
+        ;;
+    sun50i)
+        soc="A64"
+        ;;
+    'Generic AM33XX'*)
+        soc="AM33XX"
+        ;;
+    *)
+        soc="unknown"
+    esac
+    echo "${soc} ${tp} ${cpu}"
+}
+
+function gcc_cpu_flags {
+    local soc=$1
+    case $soc in
+    BCM2835)
+        flags="-march=armv6zk -mtune=arm1176jzf-s -mfpu=vfp -mfloat-abi=hard"
+        ;;
+    BCM2836)
+        flags="-march=armv7-a -mtune=cortex-a7 -mfpu=neon-vfpv4 -mfloat-abi=hard"
+        ;;
+    AM33XX)
+        flags="-march=armv7-a -mtune=cortex-a8 -mfpu=neon -mfloat-abi=hard"
+        ;;
+    A10)
+        flags="-march=armv7-a -mtune=cortex-a8 -mfpu=neon -mfloat-abi=hard"
+        ;;
+    A13)
+        flags="-march=armv7-a -mtune=cortex-a8 -mfpu=neon -mfloat-abi=hard"
+        ;;
+    A20)
+        flags="-march=armv7-a -mtune=cortex-a7 -mfpu=neon-vfpv4 -mfloat-abi=hard"
+        ;;
+    *)
+        flags=""
+    esac
+    echo ${flags}
+}
+
+function detect_driver {
+    if [[ $(execute_check 'ls /dev/spidev* 2>/dev/null') ]]; then
+        result=SPIDEV
+    elif [[ $(execute_check "cat /proc/cpuinfo | grep Hardware | grep 'BCM2708\|BCM2709'") ]]; then
+        result=RPi
+    elif [[ $(execute_check "${REMOTE_LDCONFIG} -p | grep libmraa") ]]; then
+        result=MRAA
+    elif [[ $(execute_check "${REMOTE_LDCONFIG} -p | grep liblittlewire-spi") ]]; then
+        result=LittleWire
+    else
+        result=""
+    fi
+    echo $result
+}
+
+params="OS SOC DRIVER CPUFLAGS CFLAGS PREFIX REMOTE_PREFIX LIB LIBNAME CC CXX LIB_DIR REMOTE_LIB_DIR HEADER_DIR REMOTE_HEADER_DIR DRIVER_DIR ARCH_DIR REMOTE REMOTE_HOST REMOTE_USER REMOTE_PORT SHARED_LINKER_FLAGS LDCONFIG REMOTE_LDCONFIG EXAMPLES_DIR REMOTE_EXAMPLES_DIR"
+
+for opt do
+    if [ "$opt" = "-h" ] || [ "$opt" = "--help" ]; then
         help
         exit 0
     fi
-    found=0
-    for param in ${params}; do
-        if [[ "$i" = ${param}=* ]]; then
-            eval ${param}="${i#*=}"
-            shift
-            found=1
-            break
-        fi
-    done
-    if [ "$found" = "0" ]; then
-        echo "[ERROR] Unknown option detected: ${i}"
-        exit 1
-    fi
+    optarg="${opt#*=}"
+    case "$opt" in
+    --os=*)
+        OS="$optarg"
+        ;;
+    --soc=*)
+        SOC="$optarg"
+        ;;
+    --cpu-flags=*)
+        CPUFLAGS="$optarg"
+        ;;
+    --extra-cflags=*)
+        CFLAGS="$optarg"
+        ;;
+    --extra-ldflags=*)
+        LDFLAGS="$optarg"
+        ;;
+    --libname=*)
+        LIB="$optarg"
+        ;;
+    --c_compiler=*)
+        CC="$optarg"
+        ;;
+    --cxx_compiler=*)
+        CXX="$optarg"
+        ;;
+    --prefix=*)
+        PREFIX="$optarg"
+        ;;
+    --lib-dir=*)
+        LIB_DIR="$optarg"
+        ;;
+    --header-dir=*)
+        HEADER_DIR="$optarg"
+        ;;
+    --examples-dir=*)
+        EXAMPLES_DIR="$optarg"
+        ;;
+    --ldconfig=*)
+        LDCONFIG="$optarg"
+        ;;
+    --driver=*)
+        DRIVER="$optarg"
+        ;;
+    --remote-host=*)
+        REMOTE_HOST="$optarg"
+        ;;
+    --remote-user=*)
+        REMOTE_USER="$optarg"
+        ;;
+    --remote-port=*)
+        REMOTE_PORT="$optarg"
+        ;;
+    --remote=*)
+        REMOTE="$optarg"
+        ;;
+    --remote-prefix=*)
+        REMOTE_PREFIX="$optarg"
+        ;;
+    --remote-lib-dir=*)
+        REMOTE_LIB_DIR="$optarg"
+        ;;
+    --remote-header-dir=*)
+        REMOTE_HEADER_DIR="$optarg"
+        ;;
+    --remote-ldconfig=*)
+        REMOTE_LDCONFIG="$optarg"
+        ;;
+    --remote-examples-dir=*)
+        REMOTE_EXAMPLES_DIR="$optarg"
+        ;;
+    *)
+        echo "[WARNING] Unknown option detected:$opt, ignored"
+        ;;
+    esac
 done
 
 #*******************************************
@@ -49,24 +255,29 @@ if [ "${REMOTE_HOST}" ]; then
     else
         REMOTE=${REMOTE_HOST}
     fi
+fi
+if [ "${REMOTE}" ]; then
+    echo "[SECTION] Checking remote host."
+    if [ -z "${REMOTE_HOST}" ]; then
+        REMOTE_HOST=${REMOTE/*@/}
+    fi
     if [ -z "${REMOTE_PORT}" ]; then
         REMOTE_PORT=22
     fi
-    echo "[SECTION] Checking remote host."
     if [ "$(nmap ${REMOTE_HOST} -Pn  --host-timeout 30s -p ${REMOTE_PORT} 2>/dev/null | grep open)" ]; then
         echo "  [OK] ssh daemon on ${REMOTE_HOST} port ${REMOTE_PORT} seems to be listening."
     else
         echo "  [WARNING] ssh on ${REMOTE_HOST} port ${REMOTE_PORT} seems not to be listening or nmap not installed."
     fi
-    if [[ "$(execute_check 'echo ok 2>/dev/null')" ]]; then
+    if [[ "$(execute_check 'echo ok 2>/dev/null' 2>/dev/null)" ]]; then
         echo "  [OK] Remote machine ssh passwordless login configured fine."
     else
-        echo "  [WARNING] Remote machine ssh and/or passwordless login check failed."
+        die "Remote machine ssh and/or passwordless login check failed." 1
     fi
     if [[ $(execute_check "sudo echo ok 2>/dev/null") ]]; then
         echo "  [OK] Remote machine sudo configured fine."
     else
-        echo "  [WARNING] Remote machine sudo test failed."
+        die "Remote machine sudo test failed." 1
     fi
 fi
 
@@ -109,51 +320,31 @@ CC=${CC:-gcc}
 CXX=${CXX:-g++}
 ARCH_DIR=${ARCH_DIR:-utility}
 
-#*******************************************
-# CPU detection
-if [ -z "${ARCH}" ]; then
-    echo "[SECTION] Detecting CPU architecture."
-    ARCH_DETECT=$(execute_check "uname -m")
-    echo "  [INFO] ${ARCH_DETECT} detected."
-    case ${ARCH_DETECT} in
-    armv6l)
-        echo "  [OK] Using armv6zk as ARCH."
-        ARCH=armv6zk
-        ;;
-    armv7l)
-        echo "  [OK] Using armv7-a as ARCH."
-        ARCH=armv7-a
-        ;;
-    *)
-        echo "  [INFO] No explicit ARCH set."
-        ;;
-    esac
+
+if [ -z "${SOC}" ]; then
+    echo "[SECTION] Detecting target machine."
+    info=($(detect_machine))
+    SOC=${info[0]}
+    TYPE=${info[1]}
+    CPU=${info[2]}
+    echo "[OK] machine detected: SoC=${SOC}, Type=${TYPE}, CPU=${CPU}."
 fi
 
-if [ "${ARCH}" ]; then
-    CFLAGS+=" -march=${ARCH}"
+if [ -z "${CPUFLAGS}" ]; then
+    CPUFLAGS=$(gcc_cpu_flags $SOC)
 fi
+
 
 #*******************************************
 # DRIVER detection
 if [ -z "${DRIVER}" ]; then
     echo "[SECTION] Detecting DRIVER"
-    if [[ $(execute_check 'ls /dev/spidev* 2>/dev/null') ]]; then
-        DRIVER=SPIDEV
-    elif [[ $(execute_check "cat /proc/cpuinfo | grep Hardware | grep 'BCM2708\|BCM2709'") ]]; then
-        DRIVER=RPi
-    elif [[ $(execute_check "${REMOTE_LDCONFIG} -p | grep libmraa") ]]; then
-        DRIVER=MRAA
-    elif [[ $(execute_check "${REMOTE_LDCONFIG} -p | grep liblittlewire-spi") ]]; then
-        DRIVER=LittleWire
-   else
-        echo "  [ERROR] No supported platform detected. Run configure with DRIVER=<platform> to set a platform explicitly."
-        exit 1
+    DRIVER=$(detect_driver)
+    if [ -z "${DRIVER}" ]; then
+        die "No supported driver detected. Run configure with DRIVER=<driver> to set a driver explicitly."
     fi
     echo "  [OK] DRIVER detected:${DRIVER}."
 fi
-
-
 
 case ${DRIVER} in
 SPIDEV)
@@ -168,8 +359,7 @@ LittleWire)
     SHARED_LINKER_FLAGS+=" -llittlewire-spi"
     ;;
 *)
-    echo "[ERROR] Unsupported DRIVER: ${DRIVER}."
-    exit 1
+    die "Unsupported DRIVER: ${DRIVER}." 1
     ;;
 esac
 
@@ -192,15 +382,14 @@ DARWIN)
     SHARED_LINKER_FLAGS+=" -dynamiclib -install_name ${LIB_DIR}/lib${LIB}.${DYN_SUFFIX}"
     ;;
 *)
-    echo "[ERROR] Unsupported OS: ${OS}."
-    exit 1
+    die "Unsupported OS: ${OS}." 1
     ;;
 esac
 
 
 LIBNAME=${LIBNAME:-lib${LIB}.${DYN_SUFFIX}}
 DRIVER_DIR=${DRIVER_DIR:-${ARCH_DIR}/${DRIVER}}
-CFLAGS+=" -O2 -Wall -g"
+CFLAGS="$CPUFLAGS -O2 -Wall -g $CFLAGS"
 
 echo "[SECTION] Preparing configuration."
 cp ${DRIVER_DIR}/includes.h ${ARCH_DIR}/includes.h
